### ISSUE TITLE
The wireshark monitoring service should be executed with network_mode: host

### ISSUE THREAD

**Issue by antoniomartinelli** [giper45/DockerSecurityPlayground#52]
When running the wireshark monitoring service you basically dont see any meaningful traffic.

A complete an solution can be to run the container with the flag *"network_mode: host"* in order to sniff all the traffic flowing through the host.

**Comment by giper45** [comment]
Hi @antoniomartinelli , I was thinking to wireshark monitoring service as a "reader" for captured pcap files acquired with "Start Capture" action. 
Each "hacking tool" (managed or not) binds a "dsp" shared volume.  Tcpdump stores captured sessions in /dsp directory, wireshark binds dsp_volume under /home/wireshark directory:   
![image](https://user-images.githubusercontent.com/18548727/87717641-04175c00-c7b1-11ea-8fe6-4df575b5cf98.png)

Anyway, it could be useful to use wireshark as a monitoring service. host network_mode should not give problems to actual behaviour.

**Comment by giper45** [comment]
Added network_mode support in DSP version 3.7.7 ([PR](https://github.com/giper45/DockerSecurityPlayground/commit/fa9fcb4fdb4e8e4041550863757de2cc400de1af)) .   
As [dockerjs ](https://www.npmjs.com/package/mydockerjs) library is changed to support host network mode, remember to update npm packages before updating DSP (npm update && git pull). 
If everything is okay, we close the issue. 
Thanks for the suggestion.
