### ISSUE TITLE
Unable to access DSP on a remote server because of "host" parameter in function server.listen 

### ISSUE THREAD

**Issue by ale753** [giper45/DockerSecurityPlayground#59]
**Describe the bug**

In order to access the service opened on port 8080 (Tested with a Ubuntu 20.04.1 LTS server and a Kali Linux server. ) the parameter "host" must be removed from the function server.listen in index.js.

So this function :
```

server.listen(port, host, () => {
  if (localConfig.config.test) { log.warn('Testing mode enabled'); }
  log.info(`Server listening on ${host}:${port}`);
});

```
Should become 

```
server.listen(port, () => {
  if (localConfig.config.test) { log.warn('Testing mode enabled'); }
  log.info(`Server listening on ${host}:${port}`);
});

```

**To Reproduce**
1.Install DSP on a remote server
2. Try Access DSP service through http:/"publicipofserver":8080

**Additional notes**
The application works fine on the local machine ( http://localhost:8080/ ) without the parameter host if I modify the index.js file and 
run the app with "sudo npm start". This is tested with Linux 5.9.0-kali1-amd64 on Kali Linux 2020

**Comment by giper45** [comment]
Hi @ale753 ,
default hostname is on 127.0.0.1: 
![image](https://user-images.githubusercontent.com/18548727/98482359-279f6000-2201-11eb-99d9-b2e5dc03e189.png)

before starting DSP, you should set HOSTNAME environment variable: 
```
# better to use the ip of the interface you are going to use 
export HOSTNAME=0.0.0.0 
``` 
Then, you can use DSP in a remote way.
